services:
  core:
    image: ghcr.io/www-printf/wepress-core:latest
    container_name: wepress_core
    restart: unless-stopped
    networks:
      - traefik-public
      - deploy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
