services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - internal
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.enable=true"
