services:
  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.91.3
    container_name: victoria-metrics
    restart: unless-stopped
    volumes:
      - vm-data:/storage
      - ./monitoring/victoria-metrics:/etc/prometheus
    command:
      - '--storageDataPath=/storage'
      - '--httpListenAddr=:8428'
      - '--retentionPeriod=1y'
      - '--search.maxUniqueTimeseries=3000000'
      - '--search.maxQueryDuration=1m'
      - '--dedup.minScrapeInterval=15s'
      - '--promscrape.config=/etc/prometheus/prometheus.yml'
      - '--promscrape.maxScrapeSize=64MB'
      - '--promscrape.config.strictParse=false'
    networks:
      - deploy
      - traefik-public
  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    networks:
      - deploy
      - traefik-public
    labels:
      org.label-schema.group: "monitoring"