http:
  routers:
    grafana:
      rule: "Host(`grafana.printf.store`)"
      service: grafana
      entryPoints:
        - websecure
      middlewares:
        - secure-headers
        - rate-limit

    victoria-metrics:
      rule: "Host(`metrics.printf.store`)"
      service: victoria-metrics
      entryPoints:
        - websecure
      middlewares:
        - secure-headers
        - rate-limit

    app:
      rule: "Host(`printf.store`)"
      service: app
      entryPoints:
        - websecure
      middlewares:
        - secure-headers
        - compression

    core:
      rule: "Host(`api.printf.store`)"
      service: core
      entryPoints:
        - websecure
      middlewares:
        - secure-headers
        - rate-limit

    dashboard:
      rule: "Host(`dashboard.printf.store`)"
      service: api@internal

  services:
    grafana:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"

    victoria-metrics:
      loadBalancer:
        servers:
          - url: "http://victoria-metrics:8428"

    app:
      loadBalancer:
        servers:
          - url: "http://app:80"

    core:
      loadBalancer:
        servers:
          - url: "http://core:8000"
