global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "victoria-metrics"
    static_configs:
      - targets: ["localhost:8428"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8080"]
